env:
  NEBULA_ADDRESS: "ng-uat-01.vesoft-inc.com:9669"
  NEBULA_USER: "harris"
  NEBULA_PASSWORD: "Nebula2025.harris"
  NEBULA_CONCURRENCY: 1
  NEBULA_ITERATIONS_PER_CONCURRENCY: 10
  NEBULA_STATEMENT: "use sf1 match p=(v)->(v1) return p limit 100"

jobs:
  - name: golang
    shell: |
      cd go
      go run main.go default
  
  - name: golang without scan
    shell: |
      cd go
      go run main.go no_scan
  
  - name: golang without no reuse
    shell: |
      cd go
      go run main.go no_reuse
  - name: python thread
    shell: |
      cd python
      python3 main.py thread

  - name: python process
    shell: |
      cd python
      python3 main.py process

  - name: java
    shell: |
      cd java
      mvn compile exec:java -Dexec.mainClass="com.vesoft.diffy.Main"
